### ISSUE TITLE
Nested forms not synced

### ISSUE THREAD

**Issue by aa365** [janko-m/shrine-reform#1]
I tested this with shrine master and reform 2.1.0

It works great with standalone forms but it doesn't seem to sync nested forms. I have added a failing test case here: https://github.com/aa365/shrine-reform

Before I try to create a fix, can someone please confirm if I'm setting up reform and shrine correctly? (I'm new to both libraries).

**Comment by janko** [comment]
As far as I can tell yes. Since I needed to add custom syncing code, it makes sense that nested forms aren't synced, having forgotten to handle that case. If you could find time to play with it a bit and see if you can fix it, that would be greatly appreciated.
